### ISSUE TITLE
Auto-compltion incomplete

### ISSUE THREAD

**Issue by zndynw** [dbeaver/cloudbeaver#1337]
The "auto-completion" function seems to only retrieve part of the same letter. Is there any configuration?
E.g:
500 tables starting with "T_A",
5 tables starting with "T_B",
After entering "T_B", no prompt tables
![image](https://user-images.githubusercontent.com/43458701/205597275-a8831566-c0b9-474a-8259-58730f60be13.png)
![image](https://user-images.githubusercontent.com/43458701/205598847-a7ccc988-ba4c-46f1-bcfb-b24e85c95b31.png)
![image](https://user-images.githubusercontent.com/43458701/205597908-7bf33a60-c4d1-42a4-9fd4-ec9638cbbdd1.png)

**Comment by kseniaguzeeva** [comment]
Thank you for the report. I've reproduced the bug. We will fix it.

**Comment by MarinaVorobeva21** [comment]
Fixed in 22.3.4 Milestone.

**Comment by TatyanaSsau** [comment]
I'm glad that the bug isn't actual anymore.

Feel free to ask any other questions.

**Comment by stev-tig** [comment]
Sorry to interrupt but I think I am still encountering this problem. (currently using version 23.0.4 & target db being SQL Server)

When I trigger suggestions it can suggest
![image](https://github.com/dbeaver/cloudbeaver/assets/7088592/81c1abb1-e0b8-44c2-887b-d350a1337da4)

But when trying to get "PT" tables there's no suggestions
![image](https://github.com/dbeaver/cloudbeaver/assets/7088592/f93dc513-817b-4603-9a2b-4ca3193681c0)

There are tables that starts with "PT"
![image](https://github.com/dbeaver/cloudbeaver/assets/7088592/8dd48742-47ce-4383-8a1f-817db2099775)

I have about 1k tables in the DB
![image](https://github.com/dbeaver/cloudbeaver/assets/7088592/f50e57c4-d582-41a1-8bca-bbb6d3ca5de1)

Would it be because of the number of table / objects exceeding limit? Is there any configuration that I can use?

**Comment by TatyanaSsau** [comment]
@stev-tig,
could you please try the new version? we released version 23.0.5, which includes a new SQL-editor and several enhancements to the suggestion. I recommend giving it a try as it might be beneficial for your current situation

**Comment by stev-tig** [comment]
> @stev-tig, could you please try the new version? we released version 23.0.5, which includes a new SQL-editor and several enhancements to the suggestion. I recommend giving it a try as it might be beneficial for your current situation

Thank you, @TatyanaSsau ! I tried out the new SQL editor, and it does fix the problem. Your help is much appreciated.

**Comment by TatyanaSsau** [comment]
Happy to hear it!
And thank you for your interest in CloudBeaver :)
