### ISSUE TITLE
Install Instructions Issue

### ISSUE THREAD

**Issue by FreeSoftwareServers** [dbeaver/cloudbeaver#20]
Please, describe your question in details.
```
sudo apt install nodejs
sudo apt install npm
```

causes error because NPM is already installed, confused me for a bit.

```
The following packages have unmet dependencies:
 nodejs : Conflicts: npm
```

Perhaps review install instructions again? Also, +1 for docker image! Patiently waiting, havn't got this setup yet, but looks very promising!

Update: Ran into an error when building, giving up for now, perhaps I need to pull a newer version of some software vs apt version?

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.923 s
[INFO] Finished at: 2020-04-27T18:14:07-07:00
[INFO] ------------------------------------------------------------------------
Copy server packages
Build static content
lerna notice cli v3.20.2
lerna info versioning independent
lerna info bootstrap root only
Usage: yarn [options]

yarn: error: no such option: --mutex
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'dbeaver-web'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'dbeaver-web'
lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including "@dbeaver/dbeaver"
lerna info filter [ '@dbeaver/dbeaver' ]
lerna info Executing command in 1 package: "yarn run build -- --pluginsList=../../../../pro                                                                                                                        ducts/default/plugins-list.js"
00h00m00s 0/0: : lerna ERR! yarn run build -- --pluginsList=../../../../products/default/pl                                                                                                                        ugins-list.js exited 1 in '@dbeaver/dbeaver'
lerna ERR! yarn run build -- --pluginsList=../../../../products/default/plugins-list.js std                                                                                                                        err:
ERROR: [Errno 2] No such file or directory: 'run'

lerna ERR! yarn run build -- --pluginsList=../../../../products/default/plugins-list.js exi                                                                                                                        ted 1 in '@dbeaver/dbeaver'
Copy static content
cp: cannot stat '../webapp/packages/dbeaver/dist/*': No such file or directory
Cloudbeaver is ready. Run run-server.bat in cloudbeaver folder to start the server.
root@skynet:/opt/cloudbeaver/cloudbeaver/deploy# ls
```
Update2:

Interestingly I was able to run `yarn --help` but the fix was `apt install yarn` which is not in the Wiki.

**Comment by serge-rider** [comment]
Well, if you already have npm and node then you don't need install them (note: CB needs NodeJS 12).

You have an old version of Yarn, you need to upgrade it (there is a Yarn repo, see deploy instructions).

I think we'll add Dockerfile (and probably some container) in near versions. We just released so there too many things to do :)

**Comment by allenyu6** [comment]
I am getting these errors too

yarn: error: no such option: --mutex
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'dbeaver-web'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 2 in 'dbeaver-web'
lerna notice cli v3.20.2


but upgrade yarn does not seem to help, what else I can check?

Thanks,

ALlen

**Comment by allenyu6** [comment]
I am interested in knowing if there is ever anyone has been able to successfully build and deploy based on your documents there?

**Comment by serge-rider** [comment]
@allenyu6 I've updated docs recently. As far as I know quite many people do this succesfully.
What is your yarn version?
```
yarn --version
```
Locally I have yarn 1.22.4.

Anyway we are going to publish pre-built releases starting from 1.0.2 version.

**Comment by allenyu6** [comment]
thanks for the quick reply, I have 0.32...
is that a issue?

**Comment by allenyu6** [comment]
after updated yarn to 1.22.4, I am still getting this.
![image](https://user-images.githubusercontent.com/43618477/81862444-bc1d5400-9537-11ea-9d0c-99897dd5d9a8.png)

**Comment by dkrupenya** [comment]
@allenyu6 I can see you have outdated node.js, version 8.10.0
Please, upgrade node.js to the latest LTS version

**Comment by allenyu6** [comment]
now I am able to build and start the server, but when I open the page, it shows error
![image](https://user-images.githubusercontent.com/43618477/82074816-52bd5280-96a9-11ea-9d00-2e558edf719f.png)

**Comment by allenyu6** [comment]
there is no console output for error or a log file directory (did I miss anything?)
![image](https://user-images.githubusercontent.com/43618477/82074977-8c8e5900-96a9-11ea-98ab-a2a704e4a46c.png)

**Comment by xixilin26** [comment]
I think it will be nice if you add pre-check list before build and checklist after build (before start the server)

**Comment by allenyu6** [comment]
try on Centos and Ubuntu and both built successfully, server start successfully but getting same error as above, looks like this is premature at best.  You might get it to work on your own box but I was wondering how and why it is only for a happy path.

**Comment by serge-rider** [comment]
Why do you navigate to `/dbeaver`? 
Was it somehow redirected there ?

**Comment by allenyu6** [comment]
I tried both http://hostname:8978/ and http://hostname:8978/dbeaver, both showing the same error, somewhere in the screen output, it is saying that is the root of the URI

**Comment by allenyu6** [comment]
now getting a better result.
![image](https://user-images.githubusercontent.com/43618477/82356488-a1ccf580-99d1-11ea-9961-87e98545fd0a.png)

**Comment by allenyu6** [comment]
how do I add a custom jdbc driver there?

**Comment by serge-rider** [comment]
@allenyu6 extra drivers additional is tracked in #37

This ticket seems to be resolved.
